### ISSUE TITLE
Text Command functionality broken for Japanese language environment

### ISSUE THREAD

**Issue by tomo666** [chrismaltby/gb-studio#1468]
**Describe the bug**
Show Dialogue text box does not reveal the correct menu when entering the text commands (like "!F" and "!S"). It was working in version 3.x, but broken in 4.0.
Currently, it seems like typing in the exclamation mark begins a font search. So you can enter like "!a" to show the font names that matches with the character "a". However, this is not how it should work according to the GB Studio docs.
This issue is not present in English mode (language mode set to "en"). Currently I've confirmed it is broken when switching to Japanese ("ja") for both Japanese version Windows11 and MacOS environments. May be the same for other non-en languages too.

![BugReport_GBS_text_cmd_issue_20260626](https://github.com/chrismaltby/gb-studio/assets/3715832/48a1b34a-4f88-4450-aae6-6568f423ea7c)

**To Reproduce**
1. Create a new scene and set it to show up a message dialogue.
2. Switch to Japanese language if not already
3. Type in "!F" or "!S" to reveal the font selection or speed selection.
4. Observe the functionality - it just searches for font names that matches whatever was entered after the exclamation mark

**Expected behavior**
According to the doc:
https://www.gbstudio.dev/docs/scripting/dialogue-variables
Text commands should work as documented - "!F" reveals the font name list, "!S" should reveal the speed selection menu.
Haven't tried "!Instant" or "!Cursor" but these don't work either or I'm not really sure how these work.

**Platform (please complete the following information):**
 - OS: Windows 11, MacOS 14.5
 - App version [e.g. 1.1.0]

**Comment by chrismaltby** [comment]
Thanks for raising this @tomo666 looks like that autocomplete searches based on the localised labels so `!Font` would have been `!フォント`. I think it should work as you suggest though so I've implemented a fix in https://github.com/chrismaltby/gb-studio/commit/95991799bde51a507c4301f2a16d4772144f0ddc which allows searching either with the localised label or the codes listed in the documentation.

Would you be able to test this fix works for you with the builds found at https://github.com/chrismaltby/gb-studio/actions/runs/9695712707 ? I've also updated to a newer version of [React Mentions](https://github.com/signavio/react-mentions) so it's worth checking if #1467 is still an issue with this build too

**Comment by tomo666** [comment]
Ah, multiple translation segment issue :)
Thanks for your quick action on this!
I've ran from source using the most updated build on the Development branch and confirmed !F and !C are working now (along with !Font and !Cursor). However, I have a doubt with the behavior of !S command (or !Speed). Although !S reveals the speed options, it also shows the available fonts and also shows the Cursor movement options in the selection list too. Is this expected?

<img width="231" alt="Speed_cmd_revealing_non_speed_related_options" src="https://github.com/chrismaltby/gb-studio/assets/3715832/07d2dc44-daae-4f6e-ad6c-019d74014c42">

**Comment by tomo666** [comment]
@chrismaltby Btw, I've also tried running on build: [9599179](https://github.com/chrismaltby/gb-studio/commit/95991799bde51a507c4301f2a16d4772144f0ddc) but issue #1467 was still present in this build too.

**Comment by chrismaltby** [comment]
Thanks for checking this @tomo666 I can confirm that '!S` showing fonts containing "S" also is expected behaviour (though I'll admit it's a little bit odd that it matches the "s" in cursor). If you type `!Speed` though it will filter to just show the Speed + Instant menu items. I'm considering this fixed now.

**Comment by tomo666** [comment]
Thanks @chrismaltby for confirming and fixing! All good now then 😀
